services:
  clinic-frontend:
    container_name: clinic-frontend
    build:
      context: ../
      dockerfile: Dockerfile
      target: runner
      args:
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
        DATABASE_URI: ${DATABASE_URI}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    env_file:
      - ../.env
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      DATABASE_URI: ${DATABASE_URI}
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    expose:
      - "3000"
    networks:
      - cloudflare-net

  clinic-nginx:
    image: nginx:latest
    container_name: clinic-nginx
    volumes:
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "82:80"
    depends_on:
      - clinic-frontend
    networks:
      - cloudflare-net
  # clinic-cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   container_name: clinic-cloudflared
  #   env_file:
  #     - .env
  #   command: tunnel --config /etc/cloudflared/config.yml run
  #   volumes:
  #     - ../cloudflared:/etc/cloudflared
  #   networks:
  #     - cloudflare-net
  #   restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: clinic-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cloudflare-net
    restart: always

networks:
  cloudflare-net:
    driver: bridge

volumes:
  mongo-data:
